version: '3.8'

services:
  backend:
    build:
      context: ./server
    container_name: avito-backend
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./client
    container_name: avito-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped